name: Build, Test, and Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit and integration tests
        run: dotnet test --no-build --configuration Release --logger trx --filter FullyQualifiedName~SkillSnap.Client.Tests

      - name: Run API tests
        run: dotnet test ./SkillSnap.Api/SkillSnap.Api.csproj --no-build --configuration Release --logger trx

      - name: Run Client tests
        run: dotnet test ./SkillSnap.Client.Tests/SkillSnap.Client.Tests.csproj --no-build --configuration Release --logger trx

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish API
        run: dotnet publish ./SkillSnap.Api/SkillSnap.Api.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      # Optionally, deploy Blazor WASM to Azure Static Web Apps or another service
      # - name: Publish Blazor Client
      #   run: dotnet publish ./SkillSnap.Client/SkillSnap.Client.csproj -c Release -o ./client-publish

      # - name: Deploy Blazor Client to Azure Static Web Apps
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     app_location: ./client-publish/wwwroot
      #     api_location: ""
      #     output_location: ""
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
